baseURL = "https://pierre.chalamet.net/"
languageCode = "en-us"
title = "Besides"
theme = "hyde"
author = "Pierre Chalamet"
googleAnalytics = "UA-25006917-1"
Paginate = 5

[markup]
  [markup.highlight]
    style = "vs"

[params]
  description = "dev, thoughts & rock'n roll"
  author = "Pierre Chalamet"
  avatar = "pct.png"
  links = [
    {Name = "About", URL = "/pages/about"},
    {Name = "Magnus Opera", URL = "https://github.com/MagnusOpera"},
  ]
  social = [
    { Name = "github-circled", URL = "https://github.com/pchalamet"},
    { Name = "twitter", URL = "https://twitter.com/pierrechalamet"},
    { Name = "linkedin", URL = "https://www.linkedin.com/in/pierrechalamet"},
  ]

#  themeColor = "theme-base-09"

